NAME = libft.a
CC = cc
CFLAGS = -Wall -Wextra -Werror
ARC = ar rc
FILES = ft_isdigit.c ft_memset.c ft_strjoin.c ft_strtrim.c ft_isprint.c\
		ft_strlcat.c ft_atoi.c ft_substr.c ft_putchar_fd.c\
		ft_strlcpy.c ft_tolower.c ft_bzero.c  ft_strlen.c ft_putstr_fd.c\
		ft_toupper.c ft_calloc.c ft_memchr.c ft_isalnum.c ft_striteri.c ft_putendl_fd.c\
		ft_memcmp.c ft_split.c ft_strncmp.c ft_putnbr_fd.c ft_isalpha.c ft_memcpy.c ft_strchr.c\
		ft_strnstr.c ft_isascii.c ft_memmove.c ft_strdup.c ft_strrchr.c ft_itoa.c ft_strmapi.c
FILES_B = ft_lstnew_bonus.c ft_lstsize_bonus.c ft_lstlast_bonus.c ft_lstadd_front_bonus.c\
		 ft_lstadd_back_bonus.c ft_lstadd_back_bonus.c

OBJCS = $(FILES:.c=.o)
OBJCS_B = $(FILES_B:.c=.o)
all : $(NAME)

$(NAME) : $(OBJCS) 
	@$(ARC) $(NAME) $(OBJCS)


bonus :$(OBJCS_B)
	@$(ARC) $(NAME) $(OBJCS_B)


%.o : %.c
	@$(CC) $(CFLAGS) -c $< -o $@
	@echo "\033[0;32m𝘾𝙧𝙚𝙖𝙩𝙞𝙣𝙜 ...\033[0m"
clean :
	@rm -fr $(OBJCS)
	@rm -fr $(OBJCS_B)
fclean : clean
	@rm -fr $(NAME)
re :fclean all